use chrono::{DateTime, Utc};
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::process::Command;

use super::scan_result::{ScanFinding, ScanVerdict};

type HmacSha256 = Hmac<Sha256>;

/// Per-build random 32-byte HMAC key, generated by `build.rs` and burned
/// into the binary at compile time. See build.rs for the threat-model
/// caveats — this key still lives in the binary, so a player who extracts
/// it can forge reports verifiable against THEIR build. Server-side
/// tournament validation is the only durable fix; this is the best we can
/// do client-side without a backend.
const HMAC_KEY: &[u8; 32] = include_bytes!(concat!(env!("OUT_DIR"), "/hmac_key.bin"));

/// Maximum age (seconds) a report can have before `verify` rejects it as a
/// replay. Tournament staff should treat any report older than this as stale
/// and require a fresh scan.
const REPORT_MAX_AGE_SECONDS: i64 = 30 * 60;

/// A full scan report containing all findings, machine identification, and an HMAC signature.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ScanReport {
    pub scan_id: String,
    pub timestamp: DateTime<Utc>,
    pub machine_id: String,
    pub os_info: String,
    pub overall_verdict: ScanVerdict,
    pub findings: Vec<ScanFinding>,
    pub hmac_signature: String,
}

impl ScanReport {
    /// Create a new empty report with machine_id and timestamp populated.
    pub fn new() -> Self {
        let scan_id = generate_scan_id();
        let machine_id = get_machine_id();
        let os_info = get_os_info();

        Self {
            scan_id,
            timestamp: Utc::now(),
            machine_id,
            os_info,
            overall_verdict: ScanVerdict::Clean,
            findings: Vec::new(),
            hmac_signature: String::new(),
        }
    }

    /// Add a finding to the report. Caller is responsible for invoking
    /// `compute_verdict` after the batch is complete; updating the verdict
    /// per-push made `generate_report` O(n²) in the number of findings.
    pub fn add_finding(&mut self, finding: ScanFinding) {
        self.findings.push(finding);
    }

    /// Compute the overall verdict from all findings.
    /// Priority: Flagged > Suspicious > Inconclusive > Clean. Inconclusive is
    /// surfaced only when nothing stronger was found — this keeps environmental
    /// failures (timeout, permission denied, scanner panic) visible without
    /// pretending they are cheat signals.
    pub fn compute_verdict(&self) -> ScanVerdict {
        let mut has_suspicious = false;
        let mut has_inconclusive = false;
        for f in &self.findings {
            match f.verdict {
                ScanVerdict::Flagged => return ScanVerdict::Flagged,
                ScanVerdict::Suspicious => has_suspicious = true,
                ScanVerdict::Inconclusive => has_inconclusive = true,
                ScanVerdict::Clean => {}
            }
        }
        if has_suspicious {
            ScanVerdict::Suspicious
        } else if has_inconclusive {
            ScanVerdict::Inconclusive
        } else {
            ScanVerdict::Clean
        }
    }

    /// Compute HMAC-SHA256 of the JSON content (excluding hmac_signature field)
    /// and set hmac_signature.
    pub fn sign(&mut self) {
        let content = self.signable_content();
        let mut mac = HmacSha256::new_from_slice(HMAC_KEY).expect("HMAC can take key of any size");
        mac.update(content.as_bytes());
        let result = mac.finalize();
        self.hmac_signature = hex::encode(result.into_bytes());
    }

    /// Verify the HMAC signature only. Use `verify_fresh` for the
    /// staleness-checked variant that tournament validators should call.
    pub fn verify(&self) -> bool {
        if self.hmac_signature.is_empty() {
            return false;
        }
        let content = self.signable_content();
        let mut mac = HmacSha256::new_from_slice(HMAC_KEY).expect("HMAC can take key of any size");
        mac.update(content.as_bytes());

        match hex::decode(&self.hmac_signature) {
            Ok(sig_bytes) => mac.verify_slice(&sig_bytes).is_ok(),
            Err(_) => false,
        }
    }

    /// Verify HMAC AND enforce a freshness window (rejects reports older than
    /// REPORT_MAX_AGE_SECONDS). Returns `Ok(())` on success, `Err(reason)`
    /// otherwise. This is the validator entrypoint that closes the simple
    /// replay attack: an old Clean report can no longer be reused indefinitely.
    pub fn verify_fresh(&self) -> Result<(), String> {
        if !self.verify() {
            return Err("HMAC signature invalid".to_string());
        }
        let age = Utc::now()
            .signed_duration_since(self.timestamp)
            .num_seconds();
        if age > REPORT_MAX_AGE_SECONDS {
            return Err(format!(
                "report is {}s old (max allowed: {}s) — request a fresh scan",
                age, REPORT_MAX_AGE_SECONDS
            ));
        }
        if age < -120 {
            // 2-minute clock-skew tolerance for future timestamps.
            return Err(format!(
                "report timestamp is {}s in the future — clock-skew or forgery",
                -age
            ));
        }
        Ok(())
    }

    /// Serialize the report to pretty JSON.
    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(self).unwrap_or_default()
    }

    /// Produce the JSON content used for signing (hmac_signature is set to empty string).
    fn signable_content(&self) -> String {
        let mut clone = self.clone();
        clone.hmac_signature = String::new();
        serde_json::to_string(&clone).unwrap_or_default()
    }
}

/// Generate a 256-bit random scan ID hex-encoded. Uses four independent
/// `RandomState` seeds (each ~64 bits of OS-derived entropy) plus the system
/// nanosecond clock and PID, then SHA-256s the lot to flatten distribution.
/// Two scans run in the same nanosecond by the same PID still yield distinct
/// IDs because each `RandomState::new()` draws fresh entropy.
fn generate_scan_id() -> String {
    use sha2::Digest;
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};

    let mut bytes = [0u8; 32];
    for i in 0..4 {
        let mut h = RandomState::new().build_hasher();
        h.write_u64(i as u64);
        h.write_u128(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos(),
        );
        h.write_usize(std::process::id() as usize);
        let v = h.finish();
        bytes[i * 8..(i + 1) * 8].copy_from_slice(&v.to_be_bytes());
    }
    let digest = Sha256::digest(bytes);
    hex::encode(digest)
}

/// Get the machine ID, hashed with SHA256.
fn get_machine_id() -> String {
    use sha2::Digest;
    let raw = get_raw_machine_id();
    let hash = Sha256::digest(raw.as_bytes());
    hex::encode(hash)
}

/// Platform-specific raw machine ID retrieval.
#[cfg(target_os = "macos")]
fn get_raw_machine_id() -> String {
    // Use absolute path so a hostile $PATH cannot shadow ioreg with a binary
    // returning an attacker-chosen UUID.
    let output = Command::new("/usr/sbin/ioreg")
        .args(["-rd1", "-c", "IOPlatformExpertDevice"])
        .output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            // Parse the IOPlatformUUID from the output
            for line in stdout.lines() {
                if line.contains("IOPlatformUUID") {
                    // Format: "IOPlatformUUID" = "XXXXXXXX-XXXX-..."
                    if let Some(uuid_start) = line.rfind('"') {
                        let trimmed = &line[..uuid_start];
                        if let Some(uuid_begin) = trimmed.rfind('"') {
                            return trimmed[uuid_begin + 1..].to_string();
                        }
                    }
                }
            }
            "unknown-macos".to_string()
        }
        Err(_) => "unknown-macos".to_string(),
    }
}

#[cfg(target_os = "windows")]
fn get_raw_machine_id() -> String {
    // Resolve reg.exe under SystemRoot rather than via $PATH so a binary the
    // user dropped earlier in PATH cannot return an attacker-chosen GUID.
    let sys_root = std::env::var("SystemRoot").unwrap_or_else(|_| r"C:\Windows".to_string());
    let reg_exe = format!(r"{}\System32\reg.exe", sys_root);
    let output = Command::new(&reg_exe)
        .args([
            "query",
            r"HKLM\SOFTWARE\Microsoft\Cryptography",
            "/v",
            "MachineGuid",
        ])
        .output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            // Parse the MachineGuid value from reg query output.
            // Format: MachineGuid    REG_SZ    <guid>
            // We require the parsed token to look like a GUID (32 hex chars
            // plus 4 dashes) so a malformed line ("MachineGuid REG_SZ") with
            // no value can't return "REG_SZ" as the machine_id.
            let looks_like_guid = |s: &str| -> bool {
                s.len() == 36
                    && s.chars().enumerate().all(|(i, c)| match i {
                        8 | 13 | 18 | 23 => c == '-',
                        _ => c.is_ascii_hexdigit(),
                    })
            };
            for line in stdout.lines() {
                let trimmed = line.trim();
                if trimmed.contains("MachineGuid") {
                    let parts: Vec<&str> = trimmed.split_whitespace().collect();
                    if let Some(guid) = parts.last() {
                        if looks_like_guid(guid) {
                            return (*guid).to_string();
                        }
                    }
                }
            }
            "unknown-windows".to_string()
        }
        Err(_) => "unknown-windows".to_string(),
    }
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn get_raw_machine_id() -> String {
    "unknown-platform".to_string()
}

/// Get a human-readable OS info string.
fn get_os_info() -> String {
    let _info = sysinfo::System::new_all();
    let name = sysinfo::System::name().unwrap_or_else(|| "Unknown".to_string());
    let version = sysinfo::System::os_version().unwrap_or_else(|| "Unknown".to_string());
    let arch = {
        let a = sysinfo::System::cpu_arch();
        if a.is_empty() {
            "Unknown".to_string()
        } else {
            a
        }
    };
    format!("{} {} ({})", name, version, arch)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::scan_result::{ScanFinding, ScanVerdict};
    use chrono::Duration;

    fn test_finding(verdict: ScanVerdict) -> ScanFinding {
        ScanFinding::new("test_scanner", verdict, "test finding", None)
    }

    #[test]
    fn compute_verdict_promotes_highest_severity() {
        let mut report = ScanReport::new();
        report.add_finding(test_finding(ScanVerdict::Clean));
        report.add_finding(test_finding(ScanVerdict::Inconclusive));
        report.add_finding(test_finding(ScanVerdict::Suspicious));

        assert_eq!(report.compute_verdict(), ScanVerdict::Suspicious);

        report.add_finding(test_finding(ScanVerdict::Flagged));
        assert_eq!(report.compute_verdict(), ScanVerdict::Flagged);
    }

    #[test]
    fn compute_verdict_surfaces_inconclusive_when_nothing_stronger_exists() {
        let mut report = ScanReport::new();
        report.add_finding(test_finding(ScanVerdict::Clean));
        report.add_finding(test_finding(ScanVerdict::Inconclusive));

        assert_eq!(report.compute_verdict(), ScanVerdict::Inconclusive);
    }

    #[test]
    fn signed_report_verifies_and_tampering_breaks_signature() {
        let mut report = ScanReport::new();
        report.add_finding(test_finding(ScanVerdict::Clean));
        report.overall_verdict = report.compute_verdict();
        report.sign();

        assert!(report.verify());

        report.findings.push(test_finding(ScanVerdict::Flagged));
        assert!(!report.verify());
    }

    #[test]
    fn malformed_or_missing_signature_is_rejected() {
        let mut report = ScanReport::new();
        assert!(!report.verify());

        report.hmac_signature = "not hex".to_string();
        assert!(!report.verify());
    }

    #[test]
    fn verify_fresh_rejects_stale_and_future_reports() {
        let mut stale = ScanReport::new();
        stale.timestamp = Utc::now() - Duration::seconds(REPORT_MAX_AGE_SECONDS + 1);
        stale.sign();
        assert!(stale
            .verify_fresh()
            .expect_err("stale report should fail freshness")
            .contains("old"));

        let mut future = ScanReport::new();
        future.timestamp = Utc::now() + Duration::seconds(180);
        future.sign();
        assert!(future
            .verify_fresh()
            .expect_err("future report should fail clock-skew check")
            .contains("future"));
    }

    #[test]
    fn report_json_round_trips_after_signing() {
        let mut report = ScanReport::new();
        report.add_finding(test_finding(ScanVerdict::Suspicious));
        report.overall_verdict = report.compute_verdict();
        report.sign();

        let decoded: ScanReport =
            serde_json::from_str(&report.to_json()).expect("signed report JSON should decode");
        assert_eq!(decoded.overall_verdict, ScanVerdict::Suspicious);
        assert!(decoded.verify());
    }
}
